/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.tatem.dinhunter.DinHunterAndroid ----
void stub_DinHunterAndroid_onCreate_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_DinHunterAndroid_registerBundlesReceiver_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.registerBundlesReceiver()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_checkBundles_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.checkBundles()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_continueCreating_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.continueCreating()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_createGallery_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.createGallery()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_createFeintButton_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.createFeintButton()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_createHotAppButton_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.createHotAppButton()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_showSplash_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.showSplash()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_onLoadingCompleted_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onLoadingCompleted()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_init_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.init()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_initViews_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.initViews()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_setActivityOptions_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.setActivityOptions()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_onWindowFocusChanged_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_DinHunterAndroid_onPause_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_onResume_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_onDestroy_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_finish_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.finish()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_DinHunterAndroid_onKeyDown_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_DinHunterAndroid_onBackPressed_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onBackPressed()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_DinHunterAndroid_onCreateDialog_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onCreateDialog(I)LDialog; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_DinHunterAndroid_showGallery_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.showGallery()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_hideGallery_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.hideGallery()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_onStart_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_onStop_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_createHelpView_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.createHelpView()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_createInAppInfoView_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.createInAppInfoView()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_showTutorial_26(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.showTutorial()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_hideTutorial_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.hideTutorial()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_showInAppInfo_28(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.showInAppInfo()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_hideInAppInfo_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.hideInAppInfo()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_setTutorialFile_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.setTutorialFile(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_DinHunterAndroid_putFrameOnPhoto_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.putFrameOnPhoto(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_DinHunterAndroid_showFeintButton_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.showFeintButton()V called -- fill in from the real Java impl (jadx).");
}

void stub_DinHunterAndroid_hideFeintButton_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterAndroid.hideFeintButton()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.tatem.dinhunter.DinHunterGLSurface ----
jobject stub_DinHunterGLSurface_DinHunterGLSurface_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterGLSurface.DinHunterGLSurface(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jobject stub_DinHunterGLSurface_DinHunterGLSurface_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterGLSurface.DinHunterGLSurface(LContext;LAttributeSet;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jboolean stub_DinHunterGLSurface_onTouchEvent_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterGLSurface.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_DinHunterGLSurface_dumpEvent_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterGLSurface.dumpEvent(LMotionEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.tatem.dinhunter.DinHunterRenderer ----
jobject stub_DinHunterRenderer_DinHunterRenderer_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterRenderer.DinHunterRenderer(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_DinHunterRenderer_onDrawFrame_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_DinHunterRenderer_onSurfaceChanged_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_DinHunterRenderer_onSurfaceCreated_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.DinHunterRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.tatem.dinhunter.utils.FacebookWrapper ----
jobject stub_FacebookWrapper_FacebookWrapper_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.FacebookWrapper.FacebookWrapper(LActivity;LInternetUtils;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_FacebookWrapper_logIn_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.FacebookWrapper.logIn()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookWrapper_logOut_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.FacebookWrapper.logOut()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_FacebookWrapper_isLoggedIn_45(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.FacebookWrapper.isLoggedIn()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_FacebookWrapper_publishFeed_46(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.FacebookWrapper.publishFeed(Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

jobject stub_FacebookWrapper_getUserName_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.FacebookWrapper.getUserName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

// ---- com.tatem.dinhunter.utils.InternetUtils ----
jobject stub_InternetUtils_InternetUtils_48(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.InternetUtils.InternetUtils(LActivity;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_InternetUtils_onResume_49(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.InternetUtils.onResume()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_InternetUtils_isOnline_50(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.InternetUtils.isOnline(Z)Z called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
    return JNI_FALSE;
}

void stub_InternetUtils_showOfflineDialog_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.InternetUtils.showOfflineDialog()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_openHotAppBanner_52(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.InternetUtils.openHotAppBanner()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_openMoreGames_53(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.InternetUtils.openMoreGames()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_openMarketAtPackage_54(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.InternetUtils.openMarketAtPackage(LContext;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
}

// ---- com.tatem.dinhunter.utils.SocialUtils ----
jobject stub_SocialUtils_SocialUtils_55(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.SocialUtils.SocialUtils(LActivity;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_SocialUtils_initFeint_56(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.SocialUtils.initFeint()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_openAchievements_57(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.SocialUtils.openAchievements()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_openDashboard_58(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.SocialUtils.openDashboard()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_unlockAchievement_59(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.SocialUtils.unlockAchievement(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_SocialUtils_SendFlurryEvent_60(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.dinhunter.utils.SocialUtils.SendFlurryEvent(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

// ---- org.fmod.FMODAudioDevice ----
void stub_FMODAudioDevice_start_61(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.start()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_stop_62(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.stop()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_run_63(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.run()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_shutDown_64(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.shutDown()V called -- fill in from the real Java impl (jadx).");
}

