/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern void stub_DinHunterAndroid_onCreate_0(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_registerBundlesReceiver_1(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_checkBundles_2(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_continueCreating_3(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_createGallery_4(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_createFeintButton_5(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_createHotAppButton_6(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_showSplash_7(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onLoadingCompleted_8(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_init_9(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_initViews_10(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_setActivityOptions_11(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onWindowFocusChanged_12(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onPause_13(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onResume_14(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onDestroy_15(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_finish_16(jmethodID id, va_list args);
extern jboolean stub_DinHunterAndroid_onKeyDown_17(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onBackPressed_18(jmethodID id, va_list args);
extern jobject stub_DinHunterAndroid_onCreateDialog_19(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_showGallery_20(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_hideGallery_21(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onStart_22(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_onStop_23(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_createHelpView_24(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_createInAppInfoView_25(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_showTutorial_26(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_hideTutorial_27(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_showInAppInfo_28(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_hideInAppInfo_29(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_setTutorialFile_30(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_putFrameOnPhoto_31(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_showFeintButton_32(jmethodID id, va_list args);
extern void stub_DinHunterAndroid_hideFeintButton_33(jmethodID id, va_list args);
extern jobject stub_DinHunterGLSurface_DinHunterGLSurface_34(jmethodID id, va_list args);
extern jobject stub_DinHunterGLSurface_DinHunterGLSurface_35(jmethodID id, va_list args);
extern jboolean stub_DinHunterGLSurface_onTouchEvent_36(jmethodID id, va_list args);
extern void stub_DinHunterGLSurface_dumpEvent_37(jmethodID id, va_list args);
extern jobject stub_DinHunterRenderer_DinHunterRenderer_38(jmethodID id, va_list args);
extern void stub_DinHunterRenderer_onDrawFrame_39(jmethodID id, va_list args);
extern void stub_DinHunterRenderer_onSurfaceChanged_40(jmethodID id, va_list args);
extern void stub_DinHunterRenderer_onSurfaceCreated_41(jmethodID id, va_list args);
extern jobject stub_FacebookWrapper_FacebookWrapper_42(jmethodID id, va_list args);
extern void stub_FacebookWrapper_logIn_43(jmethodID id, va_list args);
extern void stub_FacebookWrapper_logOut_44(jmethodID id, va_list args);
extern jboolean stub_FacebookWrapper_isLoggedIn_45(jmethodID id, va_list args);
extern void stub_FacebookWrapper_publishFeed_46(jmethodID id, va_list args);
extern jobject stub_FacebookWrapper_getUserName_47(jmethodID id, va_list args);
extern jobject stub_InternetUtils_InternetUtils_48(jmethodID id, va_list args);
extern void stub_InternetUtils_onResume_49(jmethodID id, va_list args);
extern jboolean stub_InternetUtils_isOnline_50(jmethodID id, va_list args);
extern void stub_InternetUtils_showOfflineDialog_51(jmethodID id, va_list args);
extern void stub_InternetUtils_openHotAppBanner_52(jmethodID id, va_list args);
extern void stub_InternetUtils_openMoreGames_53(jmethodID id, va_list args);
extern void stub_InternetUtils_openMarketAtPackage_54(jmethodID id, va_list args);
extern jobject stub_SocialUtils_SocialUtils_55(jmethodID id, va_list args);
extern void stub_SocialUtils_initFeint_56(jmethodID id, va_list args);
extern void stub_SocialUtils_openAchievements_57(jmethodID id, va_list args);
extern void stub_SocialUtils_openDashboard_58(jmethodID id, va_list args);
extern void stub_SocialUtils_unlockAchievement_59(jmethodID id, va_list args);
extern void stub_SocialUtils_SendFlurryEvent_60(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_start_61(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_stop_62(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_run_63(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_shutDown_64(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "onCreate", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 1, "registerBundlesReceiver", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 2, "checkBundles", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 3, "continueCreating", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 4, "createGallery", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 5, "createFeintButton", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 6, "createHotAppButton", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 7, "showSplash", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 8, "onLoadingCompleted", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 9, "init", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 10, "initViews", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 11, "setActivityOptions", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 12, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 13, "onPause", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 14, "onResume", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 15, "onDestroy", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 16, "finish", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 17, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.tatem.dinhunter.DinHunterAndroid
    { 18, "onBackPressed", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 19, "onCreateDialog", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.DinHunterAndroid
    { 20, "showGallery", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 21, "hideGallery", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 22, "onStart", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 23, "onStop", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 24, "createHelpView", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 25, "createInAppInfoView", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 26, "showTutorial", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 27, "hideTutorial", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 28, "showInAppInfo", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 29, "hideInAppInfo", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 30, "setTutorialFile", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 31, "putFrameOnPhoto", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 32, "showFeintButton", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 33, "hideFeintButton", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterAndroid
    { 34, "DinHunterGLSurface", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.DinHunterGLSurface
    { 35, "DinHunterGLSurface", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.DinHunterGLSurface
    { 36, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.tatem.dinhunter.DinHunterGLSurface
    { 37, "dumpEvent", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterGLSurface
    { 38, "DinHunterRenderer", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.DinHunterRenderer
    { 39, "onDrawFrame", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterRenderer
    { 40, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterRenderer
    { 41, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.tatem.dinhunter.DinHunterRenderer
    { 42, "FacebookWrapper", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.utils.FacebookWrapper
    { 43, "logIn", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.FacebookWrapper
    { 44, "logOut", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.FacebookWrapper
    { 45, "isLoggedIn", METHOD_TYPE_BOOLEAN },  // com.tatem.dinhunter.utils.FacebookWrapper
    { 46, "publishFeed", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.FacebookWrapper
    { 47, "getUserName", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.utils.FacebookWrapper
    { 48, "InternetUtils", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.utils.InternetUtils
    { 49, "onResume", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.InternetUtils
    { 50, "isOnline", METHOD_TYPE_BOOLEAN },  // com.tatem.dinhunter.utils.InternetUtils
    { 51, "showOfflineDialog", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.InternetUtils
    { 52, "openHotAppBanner", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.InternetUtils
    { 53, "openMoreGames", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.InternetUtils
    { 54, "openMarketAtPackage", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.InternetUtils
    { 55, "SocialUtils", METHOD_TYPE_OBJECT },  // com.tatem.dinhunter.utils.SocialUtils
    { 56, "initFeint", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.SocialUtils
    { 57, "openAchievements", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.SocialUtils
    { 58, "openDashboard", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.SocialUtils
    { 59, "unlockAchievement", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.SocialUtils
    { 60, "SendFlurryEvent", METHOD_TYPE_VOID },  // com.tatem.dinhunter.utils.SocialUtils
    { 61, "start", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 62, "stop", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 63, "run", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 64, "shutDown", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 0, stub_DinHunterAndroid_onCreate_0 },
    { 1, stub_DinHunterAndroid_registerBundlesReceiver_1 },
    { 2, stub_DinHunterAndroid_checkBundles_2 },
    { 3, stub_DinHunterAndroid_continueCreating_3 },
    { 4, stub_DinHunterAndroid_createGallery_4 },
    { 5, stub_DinHunterAndroid_createFeintButton_5 },
    { 6, stub_DinHunterAndroid_createHotAppButton_6 },
    { 7, stub_DinHunterAndroid_showSplash_7 },
    { 8, stub_DinHunterAndroid_onLoadingCompleted_8 },
    { 9, stub_DinHunterAndroid_init_9 },
    { 10, stub_DinHunterAndroid_initViews_10 },
    { 11, stub_DinHunterAndroid_setActivityOptions_11 },
    { 12, stub_DinHunterAndroid_onWindowFocusChanged_12 },
    { 13, stub_DinHunterAndroid_onPause_13 },
    { 14, stub_DinHunterAndroid_onResume_14 },
    { 15, stub_DinHunterAndroid_onDestroy_15 },
    { 16, stub_DinHunterAndroid_finish_16 },
    { 18, stub_DinHunterAndroid_onBackPressed_18 },
    { 20, stub_DinHunterAndroid_showGallery_20 },
    { 21, stub_DinHunterAndroid_hideGallery_21 },
    { 22, stub_DinHunterAndroid_onStart_22 },
    { 23, stub_DinHunterAndroid_onStop_23 },
    { 24, stub_DinHunterAndroid_createHelpView_24 },
    { 25, stub_DinHunterAndroid_createInAppInfoView_25 },
    { 26, stub_DinHunterAndroid_showTutorial_26 },
    { 27, stub_DinHunterAndroid_hideTutorial_27 },
    { 28, stub_DinHunterAndroid_showInAppInfo_28 },
    { 29, stub_DinHunterAndroid_hideInAppInfo_29 },
    { 30, stub_DinHunterAndroid_setTutorialFile_30 },
    { 31, stub_DinHunterAndroid_putFrameOnPhoto_31 },
    { 32, stub_DinHunterAndroid_showFeintButton_32 },
    { 33, stub_DinHunterAndroid_hideFeintButton_33 },
    { 37, stub_DinHunterGLSurface_dumpEvent_37 },
    { 39, stub_DinHunterRenderer_onDrawFrame_39 },
    { 40, stub_DinHunterRenderer_onSurfaceChanged_40 },
    { 41, stub_DinHunterRenderer_onSurfaceCreated_41 },
    { 43, stub_FacebookWrapper_logIn_43 },
    { 44, stub_FacebookWrapper_logOut_44 },
    { 46, stub_FacebookWrapper_publishFeed_46 },
    { 49, stub_InternetUtils_onResume_49 },
    { 51, stub_InternetUtils_showOfflineDialog_51 },
    { 52, stub_InternetUtils_openHotAppBanner_52 },
    { 53, stub_InternetUtils_openMoreGames_53 },
    { 54, stub_InternetUtils_openMarketAtPackage_54 },
    { 56, stub_SocialUtils_initFeint_56 },
    { 57, stub_SocialUtils_openAchievements_57 },
    { 58, stub_SocialUtils_openDashboard_58 },
    { 59, stub_SocialUtils_unlockAchievement_59 },
    { 60, stub_SocialUtils_SendFlurryEvent_60 },
    { 61, stub_FMODAudioDevice_start_61 },
    { 62, stub_FMODAudioDevice_stop_62 },
    { 63, stub_FMODAudioDevice_run_63 },
    { 64, stub_FMODAudioDevice_shutDown_64 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 17, stub_DinHunterAndroid_onKeyDown_17 },
    { 36, stub_DinHunterGLSurface_onTouchEvent_36 },
    { 45, stub_FacebookWrapper_isLoggedIn_45 },
    { 50, stub_InternetUtils_isOnline_50 },
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 19, stub_DinHunterAndroid_onCreateDialog_19 },
    { 34, stub_DinHunterGLSurface_DinHunterGLSurface_34 },
    { 35, stub_DinHunterGLSurface_DinHunterGLSurface_35 },
    { 38, stub_DinHunterRenderer_DinHunterRenderer_38 },
    { 42, stub_FacebookWrapper_FacebookWrapper_42 },
    { 47, stub_FacebookWrapper_getUserName_47 },
    { 48, stub_InternetUtils_InternetUtils_48 },
    { 55, stub_SocialUtils_SocialUtils_55 },
};

